### ISSUE TITLE
Crouton showing on Toolbar.

### ISSUE THREAD

**Issue by TostF** [keyboardsurfer/Crouton#229] opened 2015-02-06 12:31 UTC
As title says version 1.8.5 is showing croutons ON toolbar instead underneath it.
My toolbar is `setSupportActionBar` and as a part of my XML file.

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                tools:context=".ActivityOffices"
                >

    <android.support.v7.widget.Toolbar
        android:id="@+id/office_toolbar"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:minHeight="?attr/actionBarSize"
        android:background="?attr/colorPrimary" />

    <fragment
            android:id="@+id/map"
            android:name="my.app.FragmentOfficesMap"
            android:layout_below="@id/office_toolbar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </RelativeLayout>

**Comment by keyboardsurfer** [comment] 2015-02-06 13:38
Duplicate of #227

**Closed by keyboardsurfer** 2015-02-06 13:38 UTC
